.code
  PUSH 60     contract MyContract {\n
    fu...
  PUSH 40     contract MyContract {\n
    fu...
  MSTORE      contract MyContract {\n
    fu...
  CALLVALUE       contract MyContract {\n
    fu...
  PUSH [ErrorTag]       contract MyContract {\n
    fu...
  JUMPI       contract MyContract {\n
    fu...
tag 1     contract MyContract {\n
    fu...
  JUMPDEST      contract MyContract {\n
    fu...
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000      contract MyContract {\n
    fu...
  DUP1      contract MyContract {\n
    fu...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000     contract MyContract {\n
    fu...
  PUSH 0      contract MyContract {\n
    fu...
  CODECOPY      contract MyContract {\n
    fu...
  PUSH 0      contract MyContract {\n
    fu...
  RETURN      contract MyContract {\n
    fu...
.data
  0:
    .code
      PUSH 60     contract MyContract {\n
    fu...
      PUSH 40     contract MyContract {\n
    fu...
      MSTORE      contract MyContract {\n
    fu...
      PUSH 0      contract MyContract {\n
    fu...
      CALLDATALOAD      contract MyContract {\n
    fu...
      PUSH 100000000000000000000000000000000000000000000000000000000      contract MyContract {\n
    fu...
      SWAP1       contract MyContract {\n
    fu...
      DIV       contract MyContract {\n
    fu...
      PUSH FFFFFFFF     contract MyContract {\n
    fu...
      AND       contract MyContract {\n
    fu...
      DUP1      contract MyContract {\n
    fu...
      PUSH 188B85B4     contract MyContract {\n
    fu...
      EQ      contract MyContract {\n
    fu...
      PUSH [tag] 2      contract MyContract {\n
    fu...
      JUMPI       contract MyContract {\n
    fu...
      DUP1      contract MyContract {\n
    fu...
      PUSH 6817962B     contract MyContract {\n
    fu...
      EQ      contract MyContract {\n
    fu...
      PUSH [tag] 3      contract MyContract {\n
    fu...
      JUMPI       contract MyContract {\n
    fu...
    tag 1     contract MyContract {\n
    fu...
      JUMPDEST      contract MyContract {\n
    fu...
      PUSH [ErrorTag]       contract MyContract {\n
    fu...
      JUMP      contract MyContract {\n
    fu...
    tag 2     function sum(uint n) constant ...
      JUMPDEST      function sum(uint n) constant ...
      CALLVALUE       function sum(uint n) constant ...
      PUSH [ErrorTag]       function sum(uint n) constant ...
      JUMPI       function sum(uint n) constant ...
      PUSH [tag] 4      function sum(uint n) constant ...
      PUSH 4      function sum(uint n) constant ...
      DUP1      function sum(uint n) constant ...
      DUP1      function sum(uint n) constant ...
      CALLDATALOAD      function sum(uint n) constant ...
      SWAP1       function sum(uint n) constant ...
      PUSH 20     function sum(uint n) constant ...
      ADD       function sum(uint n) constant ...
      SWAP1       function sum(uint n) constant ...
      SWAP2       function sum(uint n) constant ...
      SWAP1       function sum(uint n) constant ...
      POP       function sum(uint n) constant ...
      POP       function sum(uint n) constant ...
      PUSH [tag] 5      function sum(uint n) constant ...
      JUMP      function sum(uint n) constant ...
    tag 4     function sum(uint n) constant ...
      JUMPDEST      function sum(uint n) constant ...
      PUSH 40     function sum(uint n) constant ...
      MLOAD       function sum(uint n) constant ...
      DUP1      function sum(uint n) constant ...
      DUP3      function sum(uint n) constant ...
      DUP2      function sum(uint n) constant ...
      MSTORE      function sum(uint n) constant ...
      PUSH 20     function sum(uint n) constant ...
      ADD       function sum(uint n) constant ...
      SWAP2       function sum(uint n) constant ...
      POP       function sum(uint n) constant ...
      POP       function sum(uint n) constant ...
      PUSH 40     function sum(uint n) constant ...
      MLOAD       function sum(uint n) constant ...
      DUP1      function sum(uint n) constant ...
      SWAP2       function sum(uint n) constant ...
      SUB       function sum(uint n) constant ...
      SWAP1       function sum(uint n) constant ...
      RETURN      function sum(uint n) constant ...
    tag 3     function sumtail(uint n, uint ...
      JUMPDEST      function sumtail(uint n, uint ...
      CALLVALUE       function sumtail(uint n, uint ...
      PUSH [ErrorTag]       function sumtail(uint n, uint ...
      JUMPI       function sumtail(uint n, uint ...
      PUSH [tag] 6      function sumtail(uint n, uint ...
      PUSH 4      function sumtail(uint n, uint ...
      DUP1      function sumtail(uint n, uint ...
      DUP1      function sumtail(uint n, uint ...
      CALLDATALOAD      function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      PUSH 20     function sumtail(uint n, uint ...
      ADD       function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      SWAP2       function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      DUP1      function sumtail(uint n, uint ...
      CALLDATALOAD      function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      PUSH 20     function sumtail(uint n, uint ...
      ADD       function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      SWAP2       function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      POP       function sumtail(uint n, uint ...
      POP       function sumtail(uint n, uint ...
      PUSH [tag] 7      function sumtail(uint n, uint ...
      JUMP      function sumtail(uint n, uint ...
    tag 6     function sumtail(uint n, uint ...
      JUMPDEST      function sumtail(uint n, uint ...
      PUSH 40     function sumtail(uint n, uint ...
      MLOAD       function sumtail(uint n, uint ...
      DUP1      function sumtail(uint n, uint ...
      DUP3      function sumtail(uint n, uint ...
      DUP2      function sumtail(uint n, uint ...
      MSTORE      function sumtail(uint n, uint ...
      PUSH 20     function sumtail(uint n, uint ...
      ADD       function sumtail(uint n, uint ...
      SWAP2       function sumtail(uint n, uint ...
      POP       function sumtail(uint n, uint ...
      POP       function sumtail(uint n, uint ...
      PUSH 40     function sumtail(uint n, uint ...
      MLOAD       function sumtail(uint n, uint ...
      DUP1      function sumtail(uint n, uint ...
      SWAP2       function sumtail(uint n, uint ...
      SUB       function sumtail(uint n, uint ...
      SWAP1       function sumtail(uint n, uint ...
      RETURN      function sumtail(uint n, uint ...
    tag 5     function sum(uint n) constant ...
      JUMPDEST      function sum(uint n) constant ...
      PUSH 0      uint
      PUSH [tag] 9      sumtail(n, 0)
      DUP3      n
      PUSH 0      0
      PUSH [tag] 7      sumtail
      JUMP [in]     sumtail(n, 0)
    tag 9     sumtail(n, 0)
      JUMPDEST      sumtail(n, 0)
      SWAP1       return sumtail(n, 0)
      POP       return sumtail(n, 0)
    tag 8     function sum(uint n) constant ...
      JUMPDEST      function sum(uint n) constant ...
      SWAP2       function sum(uint n) constant ...
      SWAP1       function sum(uint n) constant ...
      POP       function sum(uint n) constant ...
      JUMP [out]      function sum(uint n) constant ...
    tag 7     function sumtail(uint n, uint ...
      JUMPDEST      function sumtail(uint n, uint ...
      PUSH 0      uint
      PUSH 1      1
      DUP4      n
      EQ      n == 1
      PUSH [tag] 11     n == 1 ? acc + 1 :\n          ...
      JUMPI       n == 1 ? acc + 1 :\n          ...
      PUSH [tag] 12     sumtail(n-1, acc + n)
      PUSH 1      1
      DUP5      n
      SUB       n-1
      DUP5      n
      DUP5      acc
      ADD       acc + n
      PUSH [tag] 7      sumtail
      JUMP [in]     sumtail(n-1, acc + n)
    tag 12      sumtail(n-1, acc + n)
      JUMPDEST      sumtail(n-1, acc + n)
      PUSH [tag] 13     n == 1 ? acc + 1 :\n          ...
      JUMP      n == 1 ? acc + 1 :\n          ...
    tag 11      n == 1 ? acc + 1 :\n          ...
      JUMPDEST      n == 1 ? acc + 1 :\n          ...
      PUSH 1      1
      DUP3      acc
      ADD       acc + 1
    tag 13      n == 1 ? acc + 1 :\n          ...
      JUMPDEST      n == 1 ? acc + 1 :\n          ...
      SWAP1       return n == 1 ? acc + 1 :\n   ...
      POP       return n == 1 ? acc + 1 :\n   ...
    tag 10      function sumtail(uint n, uint ...
      JUMPDEST      function sumtail(uint n, uint ...
      SWAP3       function sumtail(uint n, uint ...
      SWAP2       function sumtail(uint n, uint ...
      POP       function sumtail(uint n, uint ...
      POP       function sumtail(uint n, uint ...
      JUMP [out]      function sumtail(uint n, uint ...
    .data